version: '2'
services:
    ukenv-app:
        image: ukenv
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ukenv-postgresql:5432/ukenv
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ukenv-postgresql:
        extends:
            file: postgresql.yml
            service: ukenv-postgresql
