version: '2'
services:
    ukenv-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/ukenv/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ukenv
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
